# Generated by Django 5.1.5 on 2025-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
